export const actions = {
    CLEAR_SEARCH: 'CLEAR_SEARCH',
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    FETCH_KEYWORDS: 'FETCH_KEYWORDS',
    FETCH_KEYWORDS_SUCCEEDED: 'FETCH_KEYWORDS_SUCCEEDED',
    FETCH_KEYWORDS_FAILED: 'FETCH_KEYWORDS_FAILED',
    SEND_CONTACT: 'SEND_CONTACT',
    SET_RESULTS: 'SET_RESULTS',
    SEARCH_TEXT: 'SEARCH_TEXT',
}